### ISSUE TITLE
Glass Shard 2nd Voice?

### ISSUE THREAD

**Issue by midiguru23** [patheros/PathSetManuals#9]
The text for the Imprefect Double modifier seems to suggest that a second (polyphonic) voice will be emitted from the CV and gate outputs when the light is on. But that seems never to happen. Am I just missing something obvious, or is this feature not yet implemented?

Great module, by the way. I bought the expanders immediately.

--Jim Aikin (midiguru23@sbcglobal.net)

**Comment by patheros** [comment]
Good catch. So the bug is Imperfect Double (and Perfect Double) will only generate a 2nd voice if configuration already has Echo, Duet or Waterfall. I've submitted a fix for this to the library.

**Comment by patheros** [comment]
Fix is now live in version 2.0.1
